import type { Metadata } from "next";
import "./scss/styles.scss";
import Main from "@/app/ui/main";
import Header from "@/app/ui/header";

// Adding title and othe metadata
export const metadata: Metadata = {
  title: "The System",
  description: "My everything, initially generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Header />
          <Main>{children}</Main>
        </div>
      </body>
    </html>
  );
}
