import type { Metadata } from "next";
import "../scss/styles.scss";

import Header from "@/ui/components/header";
import Content from "@/ui/components/content";
import Footer from "@/ui/components/footer";

// Adding title and othe metadata
export const metadata: Metadata = {
  title: "The System",
  description: "My everything, initially generated by create-next-app@latest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          {/* TODO: Header determined by the url */}
          <Header />
          <Content>{children}</Content>
          {/* TODO: Navigation determined by the url */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
